// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfpmwcbekrjpmufghxrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mcG13Y2Jla3JqcG11ZmdoeHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNzUxNjEsImV4cCI6MjA1ODk1MTE2MX0._l4E3nLMkGv9KG-nosxttQc5x_WUiiXNVrhVuoZfRS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);