// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dchfnuaghbdxarrtxijr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjaGZudWFnaGJkeGFycnR4aWpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzEyOTQsImV4cCI6MjA1OTM0NzI5NH0.ATfblg3YpSm7t8f-SIyKJgspzXGBRlZRpoQ3_lAmxdc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);